### PR TITLE
Very small patch: added rights check

### PR DESCRIPTION
**Pull request by mame98**
If the user who runs the Setup has not the UID 0 (root or with sudo), the Setup will exit with an error, so it will not fail later after the user has might made a lot of selections...

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
:)

**Comment by antoniovazquezblanco** [comment]
I see 2 space identation. What do you think it is better, 2 or 4 spaces?

**Comment by mame98** [comment]
Oh... I think 4 spaces are cleaner, because you can see the different sections easier...

**Comment by antoniovazquezblanco** [comment]
Done!

**Comment by mame98** [comment]
Ok great! ;-)

**Pull request merged**
