### PR TITLE
Just a small fix + Some new functions

### PR DESCRIPTION
**Pull request by mame98**
This is just a small fix which fixes the problem that the Setup might crash if you choose more than one locale...

Anyways, I have tested this version and it seems to work (at least in a VirtualBox). Only the root password is not set...

I will now start to work on creating the user account / fixing the passwd issue...

### CODE REVIEW

**Comment by mame98** [comment]
Added little patch which should fix the root password setting

**Comment by mame98** [comment]
Now, the user creationg will also work!

**Comment by mame98** [comment]
I've tested the additional software thing and it seems to work! ;-) Of course the definition files are still very bad and incomplete....

**Comment by mame98** [comment]
## Package definition files

short overview about `package lists` (the files in software/):

### Syntax

``` bash
PKG1
PKG2
...
PKGn

$: CMD1
$: CMD2
...
$: CMDn
```

PKGs are just the names of the packages seperated by a `\n` (newline)...

CMDs are commands to be executed in the `arch-chroot` enviroment on `/mnt`. They can be everywhere in the file but must be prefixed with `$:`.

**_PLEASE NOTE:**_ The space between the command-prefix and the command itself is important and required!

### Example:

The GUI package list

```
xorg-server
xorg-xinit
xorg-utils
xorg-server-utils
xf86-input-mouse
xf86-input-keyboard
xf86-video-vesa
lightdm
lightdm-gtk-greeter
$: systemctl enable lightdm
```

**Comment by mame98** [comment]
what do you think about the file based additional software thing?

**Comment by antoniovazquezblanco** [comment]
It is nice!
I'm currently very busy and will have very little time although I will try to test the latest changes.

**Comment by mame98** [comment]
Ok no Problem ;-) i will no try to work on command line based Installations...

Also I noticed a minor Problem with the locales and lightdm....

**Pull request merged**
