### PR TITLE
Added Translations

### PR DESCRIPTION
**Pull request by mame98**
I've added a german translation.
To run with the translations, you have to run:
ˋLC_ALL=de python3 ArchSetupˋ for german or 
ˋLC_ALL=en python3 ArchSetupˋfor english.

If you use another language, which is not supported or use nothing (ˋpython3 ArchSetupˋ),  then it will use the builtin english translations..

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Great!

**Comment by antoniovazquezblanco** [comment]
Sorry I didn't merge. Great again! :P

**Comment by mame98** [comment]
Thank you. I will maintain the German translation in future...

**Comment by antoniovazquezblanco** [comment]
Perfect! Please check also for errors in the english one. I can also maintain Spanish and Galician.

**Comment by mame98** [comment]
Cool! I will try to check the english one...

**Pull request merged**
